import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Royal Silk Dinner Gown',
    price: 12500,
    originalPrice: 15000,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=800&auto=format&fit=crop',
    description: 'A breathtaking silk gown designed for high-end dinner events and balls. Features a delicate drape and shimmering finish.',
    rating: 4.9,
    reviews: 42,
    onSale: true,
  },
  {
    id: '2',
    name: 'Executive Office Blazer Set',
    price: 8900,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=800&auto=format&fit=crop',
    description: 'Power dressing redefined. This tailored blazer set exudes confidence and professional elegance.',
    rating: 4.8,
    reviews: 56,
    isNew: true,
  },
  {
    id: '3',
    name: 'Champagne Gold Clutch',
    price: 4200,
    category: 'Bags',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop',
    description: 'The perfect companion for your evening gown. Handcrafted with fine detailing.',
    rating: 4.7,
    reviews: 28,
  },
  {
    id: '4',
    name: 'Midnight Velvet Cocktail Dress',
    price: 9500,
    originalPrice: 12000,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop',
    description: 'Rich velvet texture that catches the light beautifully. Ideal for sophisticated cocktail parties.',
    rating: 5.0,
    reviews: 19,
    onSale: true,
  },
  {
    id: '5',
    name: 'Modern African Print Maxi',
    price: 7800,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=800&auto=format&fit=crop',
    description: 'A fusion of traditional prints and modern silhouette. For the woman who celebrates her heritage with style.',
    rating: 4.9,
    reviews: 84,
  },
  {
    id: '6',
    name: 'Pearl Drop Earrings',
    price: 2500,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1535633302704-5043dd58c910?q=80&w=800&auto=format&fit=crop',
    description: 'Timeless elegance. These pearl drops add a touch of class to any outfit.',
    rating: 4.6,
    reviews: 112,
  },
  {
    id: '7',
    name: 'Casual Chic Linen Set',
    price: 6400,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1494597564530-bc7c3e1e550e?q=80&w=800&auto=format&fit=crop',
    description: 'Relaxed luxury. Breathable high-quality linen for everyday sophistication.',
    rating: 4.7,
    reviews: 63,
    isNew: true,
  },
  {
    id: '8',
    name: 'Red Carpet Stilletos',
    price: 5800,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop',
    description: 'Walk with grace and authority. Designed for comfort without compromising on style.',
    rating: 4.5,
    reviews: 47,
  }
];
